#!/usr/bin/env python3
"""
Iceberg UniForm Metadata Verifier
==================================
Validates that Iceberg metadata generated by Delta Forge's UniForm hook is
structurally correct and data-consistent with the underlying Parquet files.

This script does NOT read the Delta transaction log at all. It reads ONLY
through the Iceberg metadata chain, proving that an external Iceberg engine
(Spark, Trino, DuckDB) would see the correct data.

Usage:
    python3 verify_iceberg_metadata.py <table_path> [--verbose]

The table_path should point to the root of a Delta table that has UniForm
enabled (i.e. it has both _delta_log/ and metadata/ directories).

Checks performed:
  1. metadata/ directory exists with v{N}.metadata.json
  2. metadata.json is valid JSON with required Iceberg fields
  3. Schema has correct field count and types
  4. Snapshot chain is valid (each snapshot references a manifest list)
  5. Manifest list Avro is parseable and references valid manifest files
  6. Manifest Avro is parseable and references existing Parquet data files
  7. DuckDB iceberg_scan() reads the data and returns expected row count
  8. Row count from Iceberg matches row count from direct Parquet read

Requirements:
    pip install duckdb fastavro
"""

import argparse
import glob
import gzip
import json
import os
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# ANSI colours for terminal output
# ---------------------------------------------------------------------------
GREEN = "\033[92m"
RED = "\033[91m"
YELLOW = "\033[93m"
CYAN = "\033[96m"
BOLD = "\033[1m"
RESET = "\033[0m"

passed = 0
failed = 0
warned = 0


def ok(msg):
    global passed
    passed += 1
    print(f"  {GREEN}\u2713{RESET} {msg}")


def fail(msg):
    global failed
    failed += 1
    print(f"  {RED}\u2717{RESET} {msg}")


def warn(msg):
    global warned
    warned += 1
    print(f"  {YELLOW}\u26a0{RESET} {msg}")


def info(msg):
    print(f"  {CYAN}\u2022{RESET} {msg}")


# ---------------------------------------------------------------------------
# Check 1: metadata/ directory structure
# ---------------------------------------------------------------------------
def check_metadata_dir(table_path):
    print(f"\n{BOLD}Check 1: Metadata directory structure{RESET}")
    meta_dir = os.path.join(table_path, "metadata")
    if not os.path.isdir(meta_dir):
        fail(f"metadata/ directory not found at {meta_dir}")
        return None

    ok("metadata/ directory exists")

    # Find version-hint.text
    hint_path = os.path.join(meta_dir, "version-hint.text")
    if os.path.isfile(hint_path):
        with open(hint_path) as f:
            hint = f.read().strip()
        ok(f"version-hint.text exists (points to version {hint})")
    else:
        warn("version-hint.text not found (non-authoritative, not fatal)")

    # Find metadata JSON files
    meta_files = sorted(glob.glob(os.path.join(meta_dir, "v*.metadata.json")))
    gz_files = sorted(glob.glob(os.path.join(meta_dir, "v*.metadata.json.gz")))

    if not meta_files and not gz_files:
        fail("No v{N}.metadata.json files found")
        return None

    all_meta = meta_files + gz_files
    latest = all_meta[-1]
    version_count = len(all_meta)
    ok(f"Found {version_count} metadata version(s), latest: {os.path.basename(latest)}")

    # Find Avro files
    avro_files = glob.glob(os.path.join(meta_dir, "*.avro"))
    if avro_files:
        manifest_lists = [f for f in avro_files if "snap-" in os.path.basename(f)]
        manifests = [f for f in avro_files if "snap-" not in os.path.basename(f)]
        ok(f"Found {len(manifest_lists)} manifest list(s) and {len(manifests)} manifest(s)")
    else:
        warn("No Avro files found in metadata/ (may be inline or first commit pending)")

    return latest


# ---------------------------------------------------------------------------
# Check 2: Parse and validate metadata.json
# ---------------------------------------------------------------------------
def check_metadata_json(meta_path, verbose=False):
    print(f"\n{BOLD}Check 2: Iceberg metadata.json validation{RESET}")

    try:
        if meta_path.endswith(".gz"):
            with gzip.open(meta_path, "rt") as f:
                metadata = json.load(f)
            ok("Gzip-compressed metadata.json parsed successfully")
        else:
            with open(meta_path) as f:
                metadata = json.load(f)
            ok("metadata.json parsed as valid JSON")
    except (json.JSONDecodeError, OSError) as e:
        fail(f"Failed to parse metadata.json: {e}")
        return None

    # Required top-level fields
    required_fields = ["format-version", "table-uuid", "location"]
    for field in required_fields:
        if field in metadata:
            ok(f"Required field '{field}' present")
        else:
            fail(f"Missing required field '{field}'")

    fmt_version = metadata.get("format-version", "?")
    info(f"Iceberg format version: {fmt_version}")

    # Schema validation
    if fmt_version == 1:
        # V1 uses top-level 'schema' (single object)
        schema = metadata.get("schema")
        if schema:
            fields = schema.get("fields", [])
            ok(f"V1 schema present with {len(fields)} field(s)")
        else:
            fail("V1 metadata missing 'schema'")
            fields = []
    else:
        # V2/V3 use 'schemas' array
        schemas = metadata.get("schemas", [])
        if schemas:
            latest_schema = schemas[-1]
            fields = latest_schema.get("fields", [])
            ok(f"V{fmt_version} schemas array has {len(schemas)} version(s), "
               f"latest schema has {len(fields)} field(s)")
        else:
            fail(f"V{fmt_version} metadata missing 'schemas' array")
            fields = []

    if verbose and fields:
        info("Schema fields:")
        for f in fields:
            info(f"    {f.get('name', '?')}: {f.get('type', '?')} "
                 f"(id={f.get('id', '?')}, required={f.get('required', '?')})")

    # Snapshots
    snapshots = metadata.get("snapshots", [])
    if snapshots:
        ok(f"Found {len(snapshots)} snapshot(s)")
        latest_snap = snapshots[-1]
        summary = latest_snap.get("summary", {})
        total_records = summary.get("total-records", "?")
        total_files = summary.get("total-data-files", "?")
        info(f"Latest snapshot: {total_records} records in {total_files} data file(s)")
    else:
        warn("No snapshots found (table may be empty or first commit pending)")

    # Partition spec
    if fmt_version == 1:
        partition_spec = metadata.get("partition-spec", [])
        if partition_spec:
            ok(f"V1 partition-spec has {len(partition_spec)} field(s)")
        else:
            info("Unpartitioned table (empty partition-spec)")
    else:
        partition_specs = metadata.get("partition-specs", [])
        if partition_specs:
            latest_spec = partition_specs[-1]
            spec_fields = latest_spec.get("fields", [])
            if spec_fields:
                ok(f"Partition spec has {len(spec_fields)} field(s): "
                   f"{[f.get('name', '?') for f in spec_fields]}")
            else:
                info("Unpartitioned table (empty partition fields)")
        else:
            info("No partition-specs array (unpartitioned)")

    # Snapshot log
    snap_log = metadata.get("snapshot-log", [])
    if snap_log:
        ok(f"Snapshot log has {len(snap_log)} entries (audit trail)")

    return metadata


# ---------------------------------------------------------------------------
# Check 3: Parse Avro manifest chain
# ---------------------------------------------------------------------------
def check_manifest_chain(table_path, metadata, verbose=False):
    print(f"\n{BOLD}Check 3: Avro manifest chain validation{RESET}")

    try:
        import fastavro
    except ImportError:
        warn("fastavro not installed — skipping Avro manifest validation")
        warn("Install with: pip install fastavro")
        return

    snapshots = metadata.get("snapshots", [])
    if not snapshots:
        warn("No snapshots to validate")
        return

    latest_snap = snapshots[-1]
    manifest_list_path = latest_snap.get("manifest-list", "")

    if not manifest_list_path:
        warn("Latest snapshot has no manifest-list path")
        return

    # Resolve the manifest list path (may be absolute or relative)
    if not os.path.isabs(manifest_list_path):
        manifest_list_path = os.path.join(table_path, manifest_list_path)

    # Try resolving from metadata/ if not found directly
    if not os.path.isfile(manifest_list_path):
        basename = os.path.basename(manifest_list_path)
        alt_path = os.path.join(table_path, "metadata", basename)
        if os.path.isfile(alt_path):
            manifest_list_path = alt_path

    if not os.path.isfile(manifest_list_path):
        fail(f"Manifest list file not found: {manifest_list_path}")
        return

    # Parse manifest list
    try:
        with open(manifest_list_path, "rb") as f:
            manifest_list_records = list(fastavro.reader(f))
        ok(f"Manifest list Avro parsed: {len(manifest_list_records)} manifest(s) referenced")
    except Exception as e:
        fail(f"Failed to parse manifest list Avro: {e}")
        return

    total_data_files = 0
    for i, ml_record in enumerate(manifest_list_records):
        manifest_path = ml_record.get("manifest_path", "")
        if verbose:
            info(f"  Manifest {i}: {os.path.basename(manifest_path)}")
            added = ml_record.get("added_data_files_count", "?")
            existing = ml_record.get("existing_data_files_count", "?")
            info(f"    added_data_files={added}, existing_data_files={existing}")

        # Resolve manifest path
        if not os.path.isabs(manifest_path):
            manifest_path = os.path.join(table_path, manifest_path)
        if not os.path.isfile(manifest_path):
            basename = os.path.basename(manifest_path)
            alt = os.path.join(table_path, "metadata", basename)
            if os.path.isfile(alt):
                manifest_path = alt

        if not os.path.isfile(manifest_path):
            fail(f"Manifest file not found: {manifest_path}")
            continue

        # Parse manifest
        try:
            with open(manifest_path, "rb") as f:
                manifest_records = list(fastavro.reader(f))
            data_file_count = len(manifest_records)
            total_data_files += data_file_count

            if verbose:
                info(f"    Contains {data_file_count} data file entries")
                for j, entry in enumerate(manifest_records):
                    df = entry.get("data_file", entry)
                    fp = df.get("file_path", "?")
                    rc = df.get("record_count", "?")
                    info(f"      [{j}] {os.path.basename(fp)} — {rc} records")
        except Exception as e:
            fail(f"Failed to parse manifest Avro: {e}")
            continue

    ok(f"Manifest chain intact: {total_data_files} data file entries total")

    # Verify data files exist on disk
    missing_files = 0
    for ml_record in manifest_list_records:
        manifest_path = ml_record.get("manifest_path", "")
        if not os.path.isabs(manifest_path):
            manifest_path = os.path.join(table_path, manifest_path)
        if not os.path.isfile(manifest_path):
            manifest_path = os.path.join(table_path, "metadata",
                                         os.path.basename(manifest_path))

        if not os.path.isfile(manifest_path):
            continue

        with open(manifest_path, "rb") as f:
            for entry in fastavro.reader(f):
                df = entry.get("data_file", entry)
                fp = df.get("file_path", "")
                if not os.path.isabs(fp):
                    fp = os.path.join(table_path, fp)
                if not os.path.isfile(fp):
                    # Try relative to table root
                    alt = os.path.join(table_path, os.path.basename(fp))
                    if not os.path.isfile(alt):
                        missing_files += 1
                        fail(f"Data file missing: {fp}")

    if missing_files == 0:
        ok("All referenced data files exist on disk")


# ---------------------------------------------------------------------------
# Check 4: DuckDB Iceberg scan comparison
# ---------------------------------------------------------------------------
def check_duckdb_iceberg_scan(table_path, metadata, verbose=False):
    print(f"\n{BOLD}Check 4: DuckDB Iceberg scan — read data through Iceberg metadata{RESET}")

    try:
        import duckdb
    except ImportError:
        warn("duckdb not installed — skipping Iceberg scan comparison")
        warn("Install with: pip install duckdb")
        return

    conn = duckdb.connect()
    try:
        conn.execute("INSTALL iceberg; LOAD iceberg;")
    except Exception as e:
        warn(f"DuckDB iceberg extension not available: {e}")
        return

    # Read via iceberg_scan
    meta_dir = os.path.join(table_path, "metadata")
    meta_files = sorted(glob.glob(os.path.join(meta_dir, "v*.metadata.json")))
    gz_files = sorted(glob.glob(os.path.join(meta_dir, "v*.metadata.json.gz")))
    all_meta = meta_files + gz_files
    if not all_meta:
        fail("No metadata files for DuckDB scan")
        return

    latest_meta = all_meta[-1]

    # Try with allow_moved_paths since manifest paths may be relative
    # or recorded with a different base path than the current location
    iceberg_rows = None
    for scan_expr in [
        f"iceberg_scan('{latest_meta}', allow_moved_paths = true)",
        f"iceberg_scan('{latest_meta}')",
    ]:
        try:
            iceberg_rows = conn.execute(
                f"SELECT COUNT(*) FROM {scan_expr}"
            ).fetchone()[0]
            ok(f"DuckDB {scan_expr.split('(')[0]}() returned {iceberg_rows} rows")
            break
        except Exception:
            continue

    if iceberg_rows is None:
        warn("DuckDB iceberg_scan() failed — manifest paths may be unresolvable "
             "(this is OK if the table was moved after creation)")

    # Read the same data directly from Parquet files
    parquet_files = glob.glob(os.path.join(table_path, "**", "*.parquet"), recursive=True)
    # Exclude metadata directory parquet files
    parquet_files = [f for f in parquet_files if "/metadata/" not in f]

    if parquet_files:
        try:
            parquet_row_count = conn.execute(
                f"SELECT COUNT(*) FROM read_parquet({parquet_files})"
            ).fetchone()[0]
            ok(f"Direct Parquet read: {parquet_row_count} rows")
        except Exception as e:
            warn(f"Direct Parquet read failed: {e}")
            parquet_row_count = None
    else:
        warn("No Parquet data files found outside metadata/")
        parquet_row_count = None

    # Compare metadata claim vs actual reads
    snapshots = metadata.get("snapshots", [])
    if snapshots:
        claimed = int(snapshots[-1].get("summary", {}).get("total-records", -1))
        if claimed >= 0:
            info(f"Metadata claims {claimed} records in latest snapshot")
            if iceberg_rows is not None and iceberg_rows == claimed:
                ok(f"Iceberg scan row count ({iceberg_rows}) matches metadata claim ({claimed})")
            elif iceberg_rows is not None:
                fail(f"Row count mismatch: iceberg_scan={iceberg_rows}, metadata claims={claimed}")

            if parquet_row_count is not None and parquet_row_count == claimed:
                ok(f"Parquet row count ({parquet_row_count}) matches metadata claim ({claimed})")
            elif parquet_row_count is not None:
                # This can legitimately differ if DELETEs use deletion vectors
                warn(f"Parquet file count ({parquet_row_count}) != metadata claim ({claimed}) "
                     f"(expected if deletion vectors or overwrites are in play)")

    if iceberg_rows is not None and parquet_row_count is not None:
        if iceberg_rows == parquet_row_count:
            ok(f"Iceberg scan and Parquet direct read agree: {iceberg_rows} rows")
        else:
            info(f"Iceberg={iceberg_rows} vs Parquet={parquet_row_count} "
                 f"(difference expected with deletion vectors)")

    # Schema comparison
    if iceberg_rows is not None:
        try:
            iceberg_cols = conn.execute(
                f"SELECT * FROM iceberg_scan('{latest_meta}') LIMIT 0"
            ).description
            col_names = [c[0] for c in iceberg_cols]
            ok(f"Iceberg schema has {len(col_names)} columns: {col_names}")

            if verbose:
                info("Sample data (first 3 rows via Iceberg):")
                sample = conn.execute(
                    f"SELECT * FROM iceberg_scan('{latest_meta}') LIMIT 3"
                ).fetchdf()
                for _, row in sample.iterrows():
                    info(f"    {dict(row)}")
        except Exception as e:
            warn(f"Could not read schema from iceberg_scan: {e}")

    conn.close()


# ---------------------------------------------------------------------------
# Check 5: Cross-version consistency (if multiple metadata versions exist)
# ---------------------------------------------------------------------------
def check_version_progression(table_path, verbose=False):
    print(f"\n{BOLD}Check 5: Metadata version progression{RESET}")

    meta_dir = os.path.join(table_path, "metadata")
    meta_files = sorted(glob.glob(os.path.join(meta_dir, "v*.metadata.json")))
    gz_files = sorted(glob.glob(os.path.join(meta_dir, "v*.metadata.json.gz")))
    all_meta = sorted(meta_files + gz_files)

    if len(all_meta) < 2:
        info("Only one metadata version — progression check skipped")
        return

    prev_snap_count = 0
    for meta_path in all_meta:
        try:
            if meta_path.endswith(".gz"):
                with gzip.open(meta_path, "rt") as f:
                    m = json.load(f)
            else:
                with open(meta_path) as f:
                    m = json.load(f)

            snap_count = len(m.get("snapshots", []))
            version_name = os.path.basename(meta_path)

            if snap_count >= prev_snap_count:
                ok(f"{version_name}: {snap_count} snapshot(s) "
                   f"(monotonically increasing)")
            else:
                fail(f"{version_name}: {snap_count} snapshots < "
                     f"previous {prev_snap_count} (regression!)")

            prev_snap_count = snap_count

            if verbose:
                snaps = m.get("snapshots", [])
                for s in snaps:
                    sid = s.get("snapshot-id", "?")
                    records = s.get("summary", {}).get("total-records", "?")
                    info(f"    snapshot {sid}: {records} records")

        except Exception as e:
            fail(f"Could not parse {os.path.basename(meta_path)}: {e}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="Verify Iceberg metadata generated by Delta Forge UniForm"
    )
    parser.add_argument(
        "table_path",
        help="Path to the Delta table root (must contain metadata/ directory)"
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Show detailed output (schemas, sample data, manifest entries)"
    )
    args = parser.parse_args()

    table_path = os.path.abspath(args.table_path)

    print(f"{BOLD}{CYAN}{'='*60}{RESET}")
    print(f"{BOLD}{CYAN}  Iceberg UniForm Metadata Verifier{RESET}")
    print(f"{BOLD}{CYAN}{'='*60}{RESET}")
    print(f"  Table: {table_path}")

    if not os.path.isdir(table_path):
        print(f"\n{RED}Error: {table_path} is not a directory{RESET}")
        sys.exit(1)

    # Check for Delta log to confirm this is a Delta table
    delta_log = os.path.join(table_path, "_delta_log")
    if os.path.isdir(delta_log):
        info(f"Delta log found — this is a Delta table with UniForm")
    else:
        warn("No _delta_log/ directory — this may be a pure Iceberg table")

    # Run checks
    latest_meta = check_metadata_dir(table_path)
    if latest_meta is None:
        print(f"\n{RED}ABORT: Cannot proceed without metadata files{RESET}")
        sys.exit(1)

    metadata = check_metadata_json(latest_meta, verbose=args.verbose)
    if metadata is None:
        print(f"\n{RED}ABORT: Cannot proceed without valid metadata.json{RESET}")
        sys.exit(1)

    check_manifest_chain(table_path, metadata, verbose=args.verbose)
    check_duckdb_iceberg_scan(table_path, metadata, verbose=args.verbose)
    check_version_progression(table_path, verbose=args.verbose)

    # Summary
    print(f"\n{BOLD}{'='*60}{RESET}")
    print(f"{BOLD}  SUMMARY{RESET}")
    print(f"{'='*60}")
    print(f"  {GREEN}\u2713 Passed: {passed}{RESET}")
    if failed:
        print(f"  {RED}\u2717 Failed: {failed}{RESET}")
    if warned:
        print(f"  {YELLOW}\u26a0 Warnings: {warned}{RESET}")

    if failed == 0:
        print(f"\n  {GREEN}{BOLD}Iceberg metadata is valid and consistent!{RESET}")
        print(f"  Any Iceberg-compatible engine can read this table.")
    else:
        print(f"\n  {RED}{BOLD}Iceberg metadata has issues — see failures above.{RESET}")

    sys.exit(1 if failed > 0 else 0)


if __name__ == "__main__":
    main()
